// scripts/preview-ratios.js
// // Read data/listings.config.js, compute Winning Power (WP) on-chain for each entry,
// and display the USDC/WP ratio sorted (so we adjust askUSDC_6dec wisely)

const { ethers } = require("hardhat");
const path = require("path");

async function main() {
  const WP_ADDR = process.env.WP_ADDR;
  const USDC_ADDR = process.env.USDC_ADDR; 
  if (!WP_ADDR) throw new Error("Missing WP_ADDR in .env");

  // Load the config generated by sepolia-scan-holdings.js (and later we can edit it)
  const listings = require(path.join(__dirname, "../data/listings.config.js"));
  if (!Array.isArray(listings) || listings.length === 0) {
    throw new Error("data/listings.config.js vacío o mal formado");
  }

  const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL);

  // Minimal ABI of WP to compute WP = amount * beta / 1e18
  const wpAbi = [
    "function wpOfTokenId(uint256 tokenId, uint256 amount) view returns (uint256)",
  ];
  const wp = new ethers.Contract(WP_ADDR, wpAbi, provider);

  // helper: USDC(6) per WP with 1e18 precision (to later format nicely)
  function pricePerWP_1e18(askUSDC_6dec, wp_e18) {
    // (askUSDC_6dec * 1e18) / wp_e18: results in USDC with 6d, but scaled to 1e18
    const ask = BigInt(askUSDC_6dec);
    const wp = BigInt(wp_e18);
    return (ask * 1_000_000_000_000_000_000n) / wp;
  }

  const rows = [];
  for (let i = 0; i < listings.length; i++) {
    const { tokenId, amount, askUSDC_6dec } = listings[i];

    // compute WP on-chain
    const wp_e18 = await wp.wpOfTokenId(tokenId, amount);

    // ratio (USDC/WP)
    const pperWP_1e18 = pricePerWP_1e18(askUSDC_6dec, wp_e18);

    // human formatting: ethers.formatUnits( … , 24 ) → (6+18) decimals:
    const ratioHuman = Number(ethers.formatUnits(pperWP_1e18, 24)); // string → number

    rows.push({
      idx: i,
      tokenId: tokenId.toString(),
      amount: amount.toString(),
      wp: wp_e18.toString(),
      askUSDC: Number(askUSDC_6dec) / 1e6,  // 6 decimales
      ratioUSDCperWP: ratioHuman,           // USDC por 1 WP
    });
  }

  // sort by ascending ratio (cheapest first)
  rows.sort((a, b) => a.ratioUSDCperWP - b.ratioUSDCperWP);

  console.log("\n--- PREVIEW (cheapest USDC per WP first) ---");
  for (const r of rows) {
    console.log(
      `#${r.idx} tokenId=${r.tokenId} amount=${r.amount} ` +
      `WP=${r.wp} askUSDC=${r.askUSDC} p/WP≈${r.ratioUSDCperWP.toFixed(6)} USDC`
    );
  }

  console.log(
    "\nAjustamos askUSDC_6dec en data/listings.config.js hasta que los ratios queden como quieramos.\n" +
    "Luego firmamos con seller-list.js y el buyer podrá elegir el más barato con BUY_INDEX.\n"
  );
}

main().catch((e) => { console.error(e); process.exit(1); });
